export const ADD_SUBCATEGORY="ADD_SUBCATEGORY"
export const ADD_SUBCATEGORY_REDUCER="ADD_SUBCATEGORY_REDUCER"
export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_REDUCER="DELETE_SUBCATEGORY_REDUCER"
export const UPDATE_SUBCATEGORY="UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_REDUCER="UPDATE_SUBCATEGORY_REDUCER"
export const GET_SUBCATEGORY="GET_SUBCATEGORY"
export const GET_SUBCATEGORY_REDUCER="GET_SUBCATEGORY_REDUCER"


export const ADD_BRAND="ADD_BRAND"
export const ADD_BRAND_REDUCER="ADD_BRAND_REDUCER"
export const DELETE_BRAND="DELETE_BRAND"
export const DELETE_BRAND_REDUCER="DELETE_BRAND_REDUCER"
export const UPDATE_BRAND="UPDATE_BRAND"
export const UPDATE_BRAND_REDUCER="UPDATE_BRAND_REDUCER"
export const GET_BRAND="GET_BRAND"
export const GET_BRAND_REDUCER="GET_BRAND_REDUCER"


export const ADD_PRODUCT="ADD_PRODUCT"
export const ADD_PRODUCT_REDUCER="ADD_PRODUCT_REDUCER"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const DELETE_PRODUCT_REDUCER="DELETE_PRODUCT_REDUCER"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const UPDATE_PRODUCT_REDUCER="UPDATE_PRODUCT_REDUCER"
export const GET_PRODUCT="GET_PRODUCT"
export const GET_PRODUCT_REDUCER="GET_PRODUCT_REDUCER"


export const ADD_MAINCATEGORY="ADD_MAINCATEGORY"
export const ADD_MAINCATEGORY_REDUCER="ADD_MAINCATEGORY_REDUCER"
export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_REDUCER="DELETE_MAINCATEGORY_REDUCER"
export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_REDUCER="UPDATE_MAINCATEGORY_REDUCER"
export const GET_MAINCATEGORY="GET_MAINCATEGORY"
export const GET_MAINCATEGORY_REDUCER="GET_MAINCATEGORY_REDUCER"




export const ADD_CART="ADD_CART"
export const ADD_CART_REDUCER="ADD_CART_REDUCER"
export const DELETE_CART="DELETE_CART"
export const DELETE_CART_REDUCER="DELETE_CART_REDUCER"
export const UPDATE_CART="UPDATE_CART"
export const UPDATE_CART_REDUCER="UPDATE_CART_REDUCER"
export const GET_CART="GET_CART"
export const GET_CART_REDUCER="GET_CART_REDUCER"


export const ADD_WISHLIST="ADD_WISHLIST"
export const ADD_WISHLIST_REDUCER="ADD_WISHLIST_REDUCER"
export const DELETE_WISHLIST="DELETE_WISHLIST"
export const DELETE_WISHLIST_REDUCER="DELETE_WISHLIST_REDUCER"
export const GET_WISHLIST="GET_WISHLIST"
export const GET_WISHLIST_REDUCER="GET_WISHLIST_REDUCER"

export const ADD_CHECKOUT="ADD_CHECKOUT"
export const ADD_CHECKOUT_REDUCER="ADD_CHECKOUT_REDUCER"
export const DELETE_CHECKOUT="DELETE_CHECKOUT"
export const DELETE_CHECKOUT_REDUCER="DELETE_CHECKOUT_REDUCER"
export const UPDATE_CHECKOUT="UPDATE_CHECKOUT"
export const UPDATE_CHECKOUT_REDUCER="UPDATE_CHECKOUT_REDUCER"
export const GET_CHECKOUT="GET_CHECKOUT"
export const GET_CHECKOUT_REDUCER="GET_CHECKOUT_REDUCER"

export const ADD_CONTACT="ADD_CONTACT"
export const ADD_CONTACT_REDUCER="ADD_CONTACT_REDUCER"
export const DELETE_CONTACT="DELETE_CONTACT"
export const DELETE_CONTACT_REDUCER="DELETE_CONTACT_REDUCER"
export const UPDATE_CONTACT="UPDATE_CONTACT"
export const UPDATE_CONTACT_REDUCER="UPDATE_CONTACT_REDUCER"
export const GET_CONTACT="GET_CONTACT"
export const GET_CONTACT_REDUCER="GET_CONTACT_REDUCER"

export const ADD_NEWLATTER="ADD_NEWLATTER"
export const ADD_NEWLATTER_REDUCER="ADD_NEWLATTER_REDUCER"
export const DELETE_NEWLATTER="DELETE_NEWLATTER"
export const DELETE_NEWLATTER_REDUCER="DELETE_NEWLATTER_REDUCER"
export const GET_NEWLATTER="GET_NEWLATTER"
export const GET_NEWLATTER_REDUCER="GET_NEWLATTER_REDUCER"



