export const ADD_SUBCATEGORY="ADD_SUBCATEGORY"
export const ADD_SUBCATEGORY_REDUCER="ADD_SUBCATEGORY_REDUCER"
export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_REDUCER="DELETE_SUBCATEGORY_REDUCER"
export const UPDATE_SUBCATEGORY="UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_REDUCER="UPDATE_SUBCATEGORY_REDUCER"
export const GET_SUBCATEGORY="GET_SUBCATEGORY"
export const GET_SUBCATEGORY_REDUCER="GET_SUBCATEGORY_REDUCER"


export const ADD_BRAND="ADD_BRAND"
export const ADD_BRAND_REDUCER="ADD_BRAND_REDUCER"
export const DELETE_BRAND="DELETE_BRAND"
export const DELETE_BRAND_REDUCER="DELETE_BRAND_REDUCER"
export const UPDATE_BRAND="UPDATE_BRAND"
export const UPDATE_BRAND_REDUCER="UPDATE_BRAND_REDUCER"
export const GET_BRAND="GET_BRAND"
export const GET_BRAND_REDUCER="GET_BRAND_REDUCER"


export const ADD_PRODUCT="ADD_PRODUCT"
export const ADD_PRODUCT_REDUCER="ADD_PRODUCT_REDUCER"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const DELETE_PRODUCT_REDUCER="DELETE_PRODUCT_REDUCER"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const UPDATE_PRODUCT_REDUCER="UPDATE_PRODUCT_REDUCER"
export const GET_PRODUCT="GET_PRODUCT"
export const GET_PRODUCT_REDUCER="GET_PRODUCT_REDUCER"


export const ADD_MAINCATEGORY="ADD_MAINCATEGORY"
export const ADD_MAINCATEGORY_REDUCER="ADD_MAINCATEGORY_REDUCER"
export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_REDUCER="DELETE_MAINCATEGORY_REDUCER"
export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_REDUCER="UPDATE_MAINCATEGORY_REDUCER"
export const GET_MAINCATEGORY="GET_MAINCATEGORY"
export const GET_MAINCATEGORY_REDUCER="GET_MAINCATEGORY_REDUCER"



